# Generated by Django 3.2.2 on 2021-05-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_prestamo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
    ]
