# Generated by Django 3.2.2 on 2021-05-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210513_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='hora_devuelta',
        ),
    ]
