# Generated by Django 3.2.2 on 2021-05-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_prestamo_hora_devuelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='hora_devuelta',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
