# Generated by Django 3.2.2 on 2021-05-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_prestamo_hora_devuelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemento',
            name='identificador',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
