# Generated by Django 3.2.2 on 2021-05-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_implemento_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='implemento',
            name='identificador',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
